USE [master]
GO

/****** Object:  Database [SimpleRealestate]    Script Date: 2014-06-20 ¿ÀÀü 7:46:10 ******/
CREATE DATABASE [SimpleRealestate]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SimpleRealestate', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SimpleRealestate.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SimpleRealestate_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SimpleRealestate_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SimpleRealestate] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimpleRealestate].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SimpleRealestate] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SimpleRealestate] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SimpleRealestate] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SimpleRealestate] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SimpleRealestate] SET ARITHABORT OFF 
GO

ALTER DATABASE [SimpleRealestate] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SimpleRealestate] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SimpleRealestate] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SimpleRealestate] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SimpleRealestate] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SimpleRealestate] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SimpleRealestate] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SimpleRealestate] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SimpleRealestate] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SimpleRealestate] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SimpleRealestate] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SimpleRealestate] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SimpleRealestate] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SimpleRealestate] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SimpleRealestate] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SimpleRealestate] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SimpleRealestate] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SimpleRealestate] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SimpleRealestate] SET  MULTI_USER 
GO

ALTER DATABASE [SimpleRealestate] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SimpleRealestate] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SimpleRealestate] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SimpleRealestate] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SimpleRealestate] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SimpleRealestate] SET  READ_WRITE 
GO


